### ISSUE TITLE
Asp.Net Core DNX 4.5.1 and 5.0

### ISSUE THREAD

**Issue by jedielson** [serilog/serilog-sinks-mongodb#10]
Hi.

Is there a goal when MongoDb Synk will be full avaliable to asp.net core?

Thanks!!!

**Comment by nblumhardt** [comment]
Hi! This should have been published a week ago via #9 but it looks like there's a problem with CI. Looking into it now.

**Comment by nblumhardt** [comment]
Fixed, this is out now.

**Comment by jedielson** [comment]
Thank you so much!!!
