### ISSUE TITLE
Could not load file or assembly 'Serilog.FullNetFx, Version=1.5.0.0'

### ISSUE THREAD

**Issue by laksh-parab** [serilog/serilog-sinks-mongodb#13]
I have .Net 4.5.2 application and I have installed `Serilog 2.1.0` and `Serilog.Sinks.MongoDB 2.0.19`
I have configured sink as 
            var log = new Seri.LoggerConfiguration()
             .WriteTo.MongoDBCapped("mongodb://localhost:27017/test", collectionName: "logs")
             .CreateLogger();

However I am getting error 
Could not load file or assembly 'Serilog.FullNetFx, Version=1.5.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10' or one of its dependencies. The system cannot find the file specified.":"Serilog.FullNetFx, Version=1.5.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10

**Comment by merbla** [comment]
Hi @laksh-parab 

The Mongo DB sink is not yet compatible with Serilog `2.1.0`.  The `Serilog.FullNetFx` is has been removed in this version.

Can you try explicitly targeting Serilog `1.5.14` in your app?

**Comment by nblumhardt** [comment]
I'll have a shot at sorting this out today :+1:

**Comment by nblumhardt** [comment]
Version 3.0 of the sink, targeting Serilog 2, is now published. Thanks all!
