### ISSUE TITLE
Sink should override EmitBatchAsync()

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog-sinks-mongodb#14]
Instead of waiting on tasks as in https://github.com/serilog/serilog-sinks-mongodb/blob/dev/src/Serilog.Sinks.MongoDB/Sinks/MongoDB/MongoDBSink.cs#L157, the sink should override `PeriodicBatchingSink.EmitBatchAsync()` and use `await`.

**Comment by Jaben** [comment]
Done in dev branch.
