### ISSUE TITLE
When Serilog writes to MongoDb, what class does it use?

### ISSUE THREAD

**Issue by jmb-mage** [serilog/serilog-sinks-mongodb#18]
Sorry for a basic question, but I wonder if there is a class in the Serilog libs that is used to fill in the blank.

`var r = await _collection.FindAsync<T>(filter);`

What class would `T` be if I am reading from the MongoDB that I just wrote to with Serilog?

**Comment by Jaben** [comment]
Try:
``` 
Serilog.Events.LogEvent
```
