### ISSUE TITLE
Can not specify a collection name in WriteTo.MongoDB()

### ISSUE THREAD

**Issue by jmb-mage** [serilog/serilog-sinks-mongodb#19]
`WriteTo.MongoDBCapped()` [allows collection name as a param.](https://github.com/serilog/serilog-sinks-mongodb/blob/1dd181678a2ffb895b6dd5d8f50bdf9bca38ac98/src/Serilog.Sinks.MongoDB/LoggerConfigurationMongoDBExtensions.cs)

Why doesn't `WriteTo.MongoDB()`  allow us to specify collection name?  Does it use one by default?

**Comment by jmb-mage** [comment]
`WriteTo.MongoDB()` uses "log" as default.

**Comment by Jaben** [comment]
Closing as this request has been implemented.

**Comment by pregoli** [comment]
I can see that "RenderedMessage" and "MessageTemplate" in mongo contain same values.. How can I setup the mongodb capped to write only "RenderedMessage"? Thank you
