### ISSUE TITLE
Publish .NETStandard NuGet package (for .NET Core support)

### ISSUE THREAD

**Issue by kalahari** [serilog/serilog-sinks-mongodb#22]
Currently only .NETFramework packages are published to NuGet. Now that MongoDB.Driver 2.3 supports .NETStandard 1.5, I don't believe there are any missing dependencies.

**Comment by Jaben** [comment]
Thanks for the PR -- I'll leave the nuget publishing to @nblumhardt  ;)

**Comment by nblumhardt** [comment]
The package published from the merge of #23 should cover this; once we're happy with it we can merge it through to master 👍
