### ISSUE TITLE
collectionName is not exposed in class LoggerConfigurationMongoDBExtensions

### ISSUE THREAD

**Issue by dsoronda** [serilog/serilog-sinks-mongodb#26]
This is from [main page](https://github.com/serilog/serilog-sinks-mongodb) :
The default collection name is `'log'`, but a custom collection can be supplied with the optional `CollectionName` parameter. 

~~~csharp
// creates custom collection `applog`
var log = new LoggerConfiguration()
    .WriteTo.MongoDB("mongodb://mymongodb/logs", collectionName: "applog")
    .CreateLogger();
~~~

There is no `CollectionName` parameter in method `MongoDB`

~~~csharp
public static class LoggerConfigurationMongoDBExtensions
  {
    public static LoggerConfiguration MongoDB(this LoggerSinkConfiguration loggerConfiguration, string databaseUrl, LogEventLevel restrictedToMinimumLevel = LogEventLevel.Verbose, int batchPostingLimit = 50, TimeSpan? period = null, IFormatProvider formatProvider = null)
    {
// ....
// We are limited only to single collection name :(
// public static readonly string DefaultCollectionName = "log";

 return loggerConfiguration.Sink((ILogEventSink) new MongoDBSink(databaseUrl, batchPostingLimit, period1, formatProvider, MongoDBSink.DefaultCollectionName, new CreateCollectionOptions()), restrictedToMinimumLevel);
}
~~~

Code fix : 

~~~csharp 
public static LoggerConfiguration MongoDB(this LoggerSinkConfiguration loggerConfiguration, string databaseUrl, LogEventLevel restrictedToMinimumLevel = LogEventLevel.Verbose, int batchPostingLimit = 50, TimeSpan? period = null, IFormatProvider formatProvider = null, string collectionName = MongoDBSink.DefaultCollectionName)
{
....
return loggerConfiguration.Sink((ILogEventSink) new MongoDBSink(databaseUrl, batchPostingLimit, period1, formatProvider, collectionName, new CreateCollectionOptions()), restrictedToMinimumLevel);
}
~~~

I need to use different collections in log database.

**Comment by nblumhardt** [comment]
Thanks for the report. Are you interested in submitting a PR with this change?

**Comment by dsoronda** [comment]
Just to note, I'm using  `Serilog.Sinks.MongoDB 3.0.0` nuget package and code above was from de-compiled assembly.

Code example from tutorials is for newer version of `Serilog.Sinks.MongoDB 3.1.0-edv` nuget package (I guess) and that is not mentioned in above example (I found that after forking branch).

I forked branch and did some code cleanup and created pull request. I hope you could merge it into main branch.

I'll close this issue and I hope that will update example with little note so there will be no more confusion.

BR
