### ISSUE TITLE
Mongodb sink throws when a dictionary key contains "."

### ISSUE THREAD

**Issue by devsko** [serilog/serilog-sinks-mongodb#29]
Hi,
the keys of a Dictionary<string,...> are used as field names. This throws an exception when a key contains "." or starts with "$". These characters should be escaped somehow.
Thanks

**Comment by steveofficer** [comment]
I would like it if keys with '.' characters were converted into nested objects.
So something like:
```
{ 
  "Source.Target1" : "Text1",
  "Source.Target2" : "Text2",
  "Source.Details.Setting" : "ABC"
}
```

Would become:
```
{ 
  "Source" : {
     "Target1" : "Text1",
     "Target2" : "Text2",
     "Details" : {
         "Setting" : "ABC"
     }
  }
}
```

**Comment by nblumhardt** [comment]
@steveofficer I think it's a very interesting scenario to consider, but probably belongs in the general Serilog code rather than as a special case in this sink (otherwise, for example, a message template like `"Hello {User.Name}"` could not be rendered correctly from the resulting data in MongoDB).

If you could raise a issue in the main Serilog repo with information about your scenario I think it'll be an interesting discussion to have.

In the case of this sink, escaping whatever property names Serilog hands to it still seems like the right behaviour to me.

**Comment by IcanBENCHurCAT** [comment]
So, I only solved for the Keys having the offensive characters, but each object within that value can be a dictionary whose keys also contain invalid characters.

Looking into a solution, will send another PR when I have something working.

**Comment by DarkXoro** [comment]
For now I just imported the repo as a class lib and changed and added the following to `GenerateBsonDocuments`

            var payloadString = payload.ToString();
            var matches = Regex.Matches(payloadString, "\\\"\\.([^\"]*)\\\":|\\\"([^\"]*)\\.\\\":|\\\"([^\"]*)\\.([^\"]*)\\\":");

            if (matches?.Any() ?? false)
            {
                var matchedValues = matches.Select(x => x.Value).Distinct().ToArray();
                foreach (var match in matchedValues)
                {
                    payloadString = payloadString.Replace(match, match.Replace(".", "-"));
                }
            }

            var bson = BsonDocument.Parse(payloadString);

It tries to find any key in the with a "." in it in any location and replaces it with a hyphen.
Its a dirty solution and probably not the most optimal, but it works.

**Comment by IcanBENCHurCAT** [comment]
Only note is that $ is another reserved character.

**Comment by khushbudesai003** [comment]
@IcanBENCHurCAT  Is this fix given for .Net Core 2.1 ?

**Comment by IcanBENCHurCAT** [comment]
> @IcanBENCHurCAT Is this fix given for .Net Core 2.1 ?

@khushbudesai003 I'm not sure what you mean. The fix that I created is in one of the dev releases for this repo. I didn't like the direction that fix was going, so I abandoned my branch.

@DarkXoro If you haven't already, please fork the repository and create a pull request for this change, I'd like to see the repo owners put this into a dev release for testing.

**Comment by DarkXoro** [comment]
@IcanBENCHurCAT I have added created a PR with the modified pattern that will fix both the period and the dollar sign

**Comment by khushbudesai003** [comment]
Thanks a lot
