### ISSUE TITLE
It's not possible to remove default properties

### ISSUE THREAD

**Issue by pregoli** [serilog/serilog-sinks-mongodb#30]
It is not possible to avoid to write the "MessageTemplate" property.
It s only possible to remove custom ones.

**Comment by nblumhardt** [comment]
One option to achieve this is by accepting a custom `ITextFormatter` to override the default formatter.

**Comment by pregoli** [comment]
Thanks for your reply but I'm talking about serilog-sinks-mongodb. If you take a look at the source code it's creating the bsonDocument from the logEvent object. There are no available params to ignore some properties.

**Comment by nblumhardt** [comment]
Ah, that's right - forgot MongoDB is BSON 👍 Thanks!

**Comment by vibs2006** [comment]
can anyone help me in removing 
"MessageTemplate" property here? I'm not able to understand the resolution from comments
![image](https://user-images.githubusercontent.com/18658498/118636443-54f14a00-b7f2-11eb-8455-2e025aa630c0.png)
My simple 3 line code
```
 IMongoDatabase database = client.GetDatabase("log");
            Log.Logger = new LoggerConfiguration().WriteTo.MongoDB(database, Serilog.Events.LogEventLevel.Verbose).CreateLogger();            
            Log.Information("This is test log {proper}",1);
```

**Comment by Jaben** [comment]
Please try the latest with the MongoDBBson() sink.

**Comment by wuzhenda** [comment]
I'm still confused.  has it done?
