### ISSUE TITLE
Sign the Assembly with a Strong Name

### ISSUE THREAD

**Issue by mirandaasm** [serilog/serilog-sinks-mongodb#31]
When building a strong-named assembly referencing this sink, one will get the warning below during the build.

CSC : warning CS8002: Referenced assembly 'Serilog.Sinks.MongoDB, Version=3.1.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

Signing the assembly with a strong name is a best practice, and would cause no side-effects whatsoever to anyone.

**Comment by nblumhardt** [comment]
Hi - thanks for the suggestion. There's a package called "Strong Namer" that might help you work around this: https://github.com/dsplaisted/strongnamer. If anyone has an opportunity to submit a PR for strong naming using the key from the main Serilog repository this would be accepted also. Thanks!

**Comment by mirandaasm** [comment]
Hi there. Thanks for the help. Yeah, I'm using a similar tool at the moment: https://github.com/brutaldev/StrongNameSigner - this one seems to fix a few of the known issues of the former, and is being actively maintained by the owner/community.

Also, it's worth mentioning that MongoDB driver itself seems to be not signed either, which is why this sink might not be signed either.

**Comment by nblumhardt** [comment]
Ah, that's right - thanks. Yes, it's impossible to sign this package because of the unsigned MongoDB driver 👍
