### ISSUE TITLE
Datetime types saved in mongodb as string

### ISSUE THREAD

**Issue by danielmontalvoh** [serilog/serilog-sinks-mongodb#33]
Hi!

I am using version **3.1.0** of **Serilog.Sinks.MongoDB** but datetime types are stored in the document as a string. It's possible to change this configuration?

![capture](https://user-images.githubusercontent.com/34135389/33440570-49e872ec-d5be-11e7-88ac-458ee5d7777f.PNG)

**Comment by nblumhardt** [comment]
Hi! Thanks for the note. It's a limitation of the JSON formatter used by this sink at the moment - it should now in the 4.0.0-dev-* versions be possible to plug in an alternative JSON formatter, but you'll need to tinker to figure out how best to achieve the required result.

This is a change we'd really like to make globally if anyone's able to send a PR.

**Comment by Jaben** [comment]
Try the latest 5.0-dev sink and switch to using the MongoDBBson() version. It will output in native BSON.

**Comment by Jaben** [comment]
Closing since this problem is solved in the new Bson Sink released in v5.
