### ISSUE TITLE
MongoDB 3.6 intergration broken

### ISSUE THREAD

**Issue by ZOXEXIVO** [serilog/serilog-sinks-mongodb#34]
Why you using Guid ? 
At current state sink does not work with MongoDB 3.6 with Guid representation issue

**Comment by nblumhardt** [comment]
Thanks for the report @ZOXEXIVO - I can review/merge a PR if anyone's able to propose a fix (I don't use this sink personally).

**Comment by matttuplin** [comment]
Any idea when a new released will be built to incorporate the merged fix?

**Comment by Jaben** [comment]
Fixed in latest release v4.1.
