### ISSUE TITLE
mongolab and serlog mongodb sink

### ISSUE THREAD

**Issue by ksobon** [serilog/serilog-sinks-mongodb#38]
I am getting this when attempting to connect to MongoDB hosted on MongoLab. 

An exception of type 'System.TimeoutException' occurred in MongoDB.Driver.Core.dll but was not handled in user code
Additional information: A timeout occured after 30000ms selecting a server using CompositeServerSelector{ Selectors = ReadPreferenceServerSelector{ ReadPreference = { Mode = Primary, TagSets = [] } }, LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 } }. Client view of cluster state is { ClusterId : "1", ConnectionMode : "Automatic", Type : "Unknown", State : "Disconnected", Servers : [{ ServerId: "{ ClusterId : 1, EndPoint : "Unspecified/ds155461.mlab.com:55461" }", EndPoint: "Unspecified/ds155461.mlab.com:55461", State: "Disconnected", Type: "Unknown" }] }.

I am using a connection string like so: 
```
var log = new LoggerConfiguration()
                .WriteTo.MongoDB("mongodb://dbuser:dbpassword@ds155461.mlab.com:55461/zombie_log", collectionName: "konradSobon")
                .CreateLogger();
```
...where `<dbuser>` and `<dbpassword>` are actual values setup in mongolab. 

Is it possible to connect to a remote db using serilog or does it have to be a local db? 

Cheers!

**Comment by mattvasc** [comment]
Hi there @ksobon, did you manage to solve this issue? I'm getting the same...

**Comment by Jaben** [comment]
Readme includes an example with credentials using the newer sink with v5.0-dev. Please try it. Closing this for now.
