### ISSUE TITLE
Error in MongoDBJsonFormatter for Exceptions ? 

### ISSUE THREAD

**Issue by ThomasGoetzmann** [serilog/serilog-sinks-mongodb#42]
I have an error when Logging exceptions
```C#
var exception = new ArgumentNullException("x");
//...
Log.Fatal(exception, "Some message...");
```

I enabled the SelfLog and that's the message I get

```log
[...]
Exception thrown: 'System.FormatException' in MongoDB.Bson.dll
Exception while emitting periodic batch from Serilog.Sinks.MongoDB.MongoDBSink: System.FormatException: JSON reader was expecting a name but found '{'.
[...]
```

I set up the logger like this:
```C#
Log.Logger = new LoggerConfiguration()
                           .Enrich.WithExceptionDetails(new DestructuringOptionsBuilder().WithDefaultDestructurers().WithRootName("Exception"))
                           .Enrich.WithDemystifiedStackTraces()
                           .Enrich.WithEnvironmentUserName()
                           .Enrich.WithMachineName()
                           .WriteTo.Async(a => a.File(path: "log-mytool.log",
                                                      restrictedToMinimumLevel: LogEventLevel.Verbose,
                                                      outputTemplate: "{Timestamp:yyyy-dd-MM HH:mm:ss K} [{Level}] {Message:lj}{NewLine}{Properties:j}{NewLine}{Exception}",
                                                      rollingInterval: RollingInterval.Day,
                                                      retainedFileCountLimit: 31,
                                                      buffered: true))
                           .WriteTo.MongoDBCapped(databaseUrl: $"mongodb://user:password@localhost:27017/database",
                                           restrictedToMinimumLevel: LogEventLevel.Debug,
                                           period: TimeSpan.Zero,
                                           collectionName: "logs",
                                           cappedMaxSizeMb: 50,
                                           cappedMaxDocuments: 10000,
                                           mongoDBJsonFormatter: new MongoDBJsonFormatter(omitEnclosingObject: false, renderMessage: true))
                          .CreateLogger();
```

After playing around, I found out that when I use the default ``MongoDBJsonFormatter`` or when I just set ``omitEnclosingObject = true`` (like in the default) I get this error:

```
[...]
Exception thrown: 'MongoDB.Bson.BsonSerializationException' in mscorlib.dll
Exception thrown: 'System.AggregateException' in mscorlib.dll
Exception while emitting periodic batch from Serilog.Sinks.MongoDB.MongoDBSink: System.AggregateException: One or more errors occurred. ---> MongoDB.Bson.BsonSerializationException: Element name 'System.Object' is not valid'.
   at MongoDB.Bson.IO.BsonWriter.WriteName(String name)
[...]
```

Log to file works fine.
Log to mongodb when serializing simple messages with or without params is also working fine

Did I mess up the configuration or does someone have an idea on how to solve this?
I suspect a problem in the MongoDBJsonFormatter where some invalid character is not escaped or replaced correctly ?

**Comment by dojo87** [comment]
In `Serilog.Helpers.MongoDbHelper.GenerateBsonDocuments` the `LogEvent` object delimeter is written twice IF the `MongoDBJsonFormatter `has `omitEnclosingObject=false`. Once by the helper method itself and then by the formatter. The helper method also tries to add `UtcTimestamp` property by just appending it with preceding comma. That means the helper method **always expects** that the formatter does not add closing curly brackets.

This is what the helper method writes:
```
{ 
   "logEvents": [
       { "event", "UtcTimestamp": ""},
       { "event", "UtcTimestamp": ""}
   ]
}
```
Where "event" is what the Formatter does to the LogEvent. If the formatter additionaly encloses with brackets, then it malforms the output:
```json
{ 
   "logEvents": [
       { { "eventlog-properties": "etc" }, "UtcTimestamp": ""},
       { { "eventlog-properties": "etc" }, "UtcTimestamp": ""}
   ]
}
```

It wouldn't be good to change MongoDBJsonFormatter defaults, as people may use an empty constructor already. In some sense it might also be treated as wrong configuration, however it would be worth having a more descriptive exception to know what's going on.

**Comment by Jaben** [comment]
Try the latest development nuget (5.0) and switch to using .MongoDBBson() sink.

**Comment by Jaben** [comment]
It's now released -- let me know if you have any problems with using the MongoDBBson() sink.
