### ISSUE TITLE
Documentation for Secure Connection Needed

### ISSUE THREAD

**Issue by vandensd** [serilog/serilog-sinks-mongodb#46]
Was really fumbling around when attempting to write to mongo sink with a password protected connection and stumbled on https://github.com/serilog/serilog-sinks-mongodb/issues/12#issuecomment-245657074.

Would be really helpful to have this in the documentation that IMongoDatabase can be used (therefore credentials added).

**Comment by dwfritz-smellin** [comment]
I would like to second this. I am using an Azure/Cosmos MongoDB and would like to use Serilog but am having difficulty setting up my secure logon
