### ISSUE TITLE
 Problem creating collection on mongodb with serilog

### ISSUE THREAD

**Issue by agilecoreapp** [serilog/serilog-sinks-mongodb#52]
I have this code below:
`Logger = new LoggerConfiguration()
                            .WriteTo.Console()
                            .WriteTo.File(path: LoggerPath)
                            .WriteTo.MongoDBCapped(database: database,
                                                   restrictedToMinimumLevel: LogEventLevel.Verbose,
                                                   collectionName: mongoCollection,
                                                   batchPostingLimit: 1,
                                                   period: TimeSpan.Zero).CreateLogger();`

And when I go to my mongodb database I can't see the collection created with the custom name.

**Comment by longletian** [comment]
.NET Core OR  Net  Framwork

**Comment by agilecoreapp** [comment]
.NET Core

**Comment by longletian** [comment]
![image](https://user-images.githubusercontent.com/28197668/83613159-f9fd1d80-a5b5-11ea-8c5f-867b3b56cc77.png)

**Comment by longletian** [comment]
not support  Net Core，

**Comment by FlippievanDyk** [comment]
Are there any plans to rectify this? 

With .Net Framework slowly but surely being replaced with Core, then 5, does this have any priority?

**Comment by Jaben** [comment]
Please try with the latest version: v5.0.0.

**Comment by Jaben** [comment]
This issue should be fixed in latest. Please reopen if you continue to have problems.
