### ISSUE TITLE
Build Nuget Deployment is Broken

### ISSUE THREAD

**Issue by Jaben** [serilog/serilog-sinks-mongodb#55]
@nblumhardt The nuget deployment is broken for the dev branch: https://ci.appveyor.com/project/serilog/serilog-sinks-mongodb/builds/35866778

I updated the build to newer .NET Core and all appears well -- except the final push.

Thanks

**Comment by nblumhardt** [comment]
Thanks for the heads-up, @Jaben 👍 

I've just updated the publishing key, it looks like the build is happy again now.
