### ISSUE TITLE
support mongo db password 

### ISSUE THREAD

**Issue by behroozbc** [serilog/serilog-sinks-mongodb#56]
hi 
I use this connection string have password and dont work 
```
{
        "Name": "MongoDB",
        "Args": {
          "databaseUrl": "mongodb://username:password@ip:port/dbName",
          "collectionName": "logs",
          "cappedMaxSizeMb": "1024",
          "cappedMaxDocuments": "50000"
        }
}
```

**Comment by Jaben** [comment]
Could you try again with latest v5.0-dev? Thanks

**Comment by behroozbc** [comment]
hi @Jaben 
I fix this in version 4 
thanks for helping 
but how I fix this ?
change database url to like this 
```"databaseUrl": "mongodb://username:password@ip:port/dbName?authSource=admin",```

**Comment by behroozbc** [comment]
I make this https://github.com/serilog/serilog-sinks-mongodb/pull/62

**Comment by pachecoder** [comment]
> hi @Jaben
> I fix this in version 4
> thanks for helping
> but how I fix this ?
> change database url to like this
> `"databaseUrl": "mongodb://username:password@ip:port/dbName?authSource=admin",`
> I think add this to document is good

Actually i was looking for this solution. Thanks.

**Comment by Jaben** [comment]
The example is in the docs -- thanks. Closing this issue!
