### ISSUE TITLE
Properties with dot cannot be inserted into MongoDB

### ISSUE THREAD

**Issue by IvaskevychYuriy** [serilog/serilog-sinks-mongodb#58]
Mongo cannot insert documents that contain properties with dots, like so:

`{ "some.property": 123 }`

Hence there are no logs produced when any of the properties contain dot character, either from injected proeprties, templated message or exception data.

There was a broken fork - https://github.com/DarkXoro/serilog-sinks-mongodb
And proposed (yet no merged) PR two years ago - https://github.com/serilog/serilog-sinks-mongodb/pull/45/ 
Previous issue (closed but not resolved) - https://github.com/serilog/serilog-sinks-mongodb/issues/29

This bug is almost two (!) years old, I'm willing to fix the previous fork and propose a new PR

**Comment by IvaskevychYuriy** [comment]
This is now in PR https://github.com/serilog/serilog-sinks-mongodb/pull/60

**Comment by Jaben** [comment]
v5.0-dev has this fix. Closing for now.
