### ISSUE TITLE
Release v4.1.0

### ISSUE THREAD

**Issue by Jaben** [serilog/serilog-sinks-mongodb#61]
@nblumhardt any issue you see releasing v4.1.0 from current dev as final release before moving to v5.0 for the BsonStructure PR?

**Comment by nblumhardt** [comment]
Sounds like a plan 👍  --- need any help with the process?

**Comment by Jaben** [comment]
@nblumhardt I could use a little help. It seems the API key is bad again:

```
Error publishing package. NuGet server returned 403: The specified API key is invalid, has expired, or does not have permission to access the specified package.
```

Thanks!

**Comment by nblumhardt** [comment]
Done! Thanks :-)

**Comment by Jaben** [comment]
Thanks @nblumhardt !
