### ISSUE TITLE
V5 regression

### ISSUE THREAD

**Issue by Nexus452** [serilog/serilog-sinks-mongodb#66]
Hi,

After updating to V5, my code no longer works.
To reproduce  :

     var logger = new LoggerConfiguration()
                .Enrich.FromLogContext()
                .WriteTo.MongoDB(
                    context.Database,
                    period: TimeSpan.FromSeconds(1),
                    batchPostingLimit: 10
                    ).WriteTo.Console()
                .CreateLogger();

            for (int i = 0; i <500; i++)
            {
                logger.Information("Tst");
                Thread.Sleep(150);
            }

It breaks in the legacy sink when writing the end of the json document :

payload.Write("]}");

Somehow the json is maflformated.

Thanks

**Comment by Jaben** [comment]
Try latest dev.
