### ISSUE TITLE
Is `RepositoryUrl ` Correct ?

### ISSUE THREAD

**Issue by behroozbc** [serilog/serilog-sinks-mongodb#69]
I see in csproj file `RepositoryUrl ` pointed to this address https://github.com/CaptiveAire/Seq.App.YouTrack but I `RepositoryUrl` think should point to this repository address

https://github.com/serilog/serilog-sinks-mongodb/blob/9cbbb819104fed170e17c0cfd2ed88ffd3756ddd/src/Serilog.Sinks.MongoDB/Serilog.Sinks.MongoDB.csproj#L16

**Comment by Jaben** [comment]
Yes -- not correct -- thanks for the PR

**Comment by behroozbc** [comment]
@Jaben thanks
I have another question 
Is copyright change to 2022?
https://github.com/serilog/serilog-sinks-mongodb/blob/9cbbb819104fed170e17c0cfd2ed88ffd3756ddd/src/Serilog.Sinks.MongoDB/Serilog.Sinks.MongoDB.csproj#L11

**Comment by Jaben** [comment]
@behroozbc Yes.
