### ISSUE TITLE
Parameters MaxDocuments and MaxSize in the class CreateCollectionOptions not effective

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog-sinks-mongodb#8]
Moved from: https://github.com/serilog/serilog/issues/651

> Parameters MaxDocuments and MaxSize in the class CreateCollectionOptions do not work.

**Comment by saleem-mirza** [comment]
I believe, MaxDocuments and MaxSize options should be removed as there is performance penalty for fetching collections stats. In order to work this feature effectively, one have to query states for each write which in my opinion is counter productive.

**Comment by nblumhardt** [comment]
Thanks for the information, I'm not familiar with MongoDB personally, but if that's the case (and the options aren't working anyway) then removing them does seem like the right thing to do :+1:

**Comment by saleem-mirza** [comment]
However, MongoDB do support a special kind of collection with such limitations but with some restrictions. Please see https://docs.mongodb.com/manual/core/capped-collections/

**Comment by nblumhardt** [comment]
Ah, thanks - that does ring some bells - I think capped collections were the original intended behavoiur here.

**Comment by Jaben** [comment]
@saleem-mirza The extension is specifically MongoDBCapped() which creates a capped collection. The other extension does not create a capped collection or use the MaxDocument/MaxSize parameters.

Why does it need to be removed? It's additional feature if you want to use a capped collection.

**Comment by Jaben** [comment]
@nblumhardt We don't use the mongo db sink anymore -- but I just pulled it down and tested the capped collection creation with latest (v2.0). Creates a capped collection and logs properly.

**Comment by saleem-mirza** [comment]
@Jaben I wasn't aware of if this extension is using capped collection and https://github.com/serilog/serilog/issues/651 reports issue, if something is not working or adding confusion, it's better to simplify it. We are targeting wast audience so need to understand what user is thinking.

I'd suggest if you can merge two collections into one and add  MaxNumberOfDocuments and MaxSizeOfCollection as optional parameter. If user provides value, create capped collection, otherwise don't.

**Comment by Jaben** [comment]
@saleem-mirza Agreed -- it's a little confusing now because the Collection Creation Options aren't even used if it's not a capped collection. I've added that feature back in and will update here soon.

**Comment by Jaben** [comment]
@saleem-mirza Please try the latest -dev (prelease) nuget and let us know if you continue to have issues with the API.

**Comment by pregoli** [comment]
I m using serilog with mongocapped. Is there a way to not write the "messageTemplate" property? Thank you
